### ISSUE TITLE
Q about tagging convention🤔

### ISSUE THREAD

**Issue by kloczek** [ColinKennedy/sphinx-code-include#8]
Is it any reason why tagging convention has been changed from `v<version>` to `v<version>` and/or is that change will be permanent? 🤔 
I'm asking because my automation is using tags.

**Comment by ColinKennedy** [comment]
I just forgot the v. I can make another tag. That said your automation really should allow for a prefix v or missing v because github repositories vary in convention in many places.

**Comment by ColinKennedy** [comment]
This is added. Sorry it took so long, I initially waited for a reply from you but didn't get notifications of your emojis so I eventually forgot. Anyway, this tag exists now. Closing this issue.

**Comment by kloczek** [comment]
Thx 👍
